services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcendence_db
    # On ne publie plus le port 5432 sur l'hôte pour plus de sécurité
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nest_backend
    restart: always
    expose:
      - "3000"
    # IMPORTANT : Charger le fichier .env
    env_file:
      - ./backend/.env
    environment:
      # On peut garder DATABASE_URL ici car elle utilise le nom du service 'db'
      DATABASE_URL: "postgresql://user:password@db:5432/transcendence_db"
      # Tu peux aussi forcer les variables ici pour être sûr à 100%
      GOOGLE_REDIRECT_URI: "https://localhost:8443/api/auth/google/callback"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - "5173"
    tty: true
    stdin_open: true

  # LE REVERSE PROXY
  gateway:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"   # Redirection HTTP -> HTTPS
      - "8443:443" # HTTPS
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend

volumes:
  pgdata: