services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcendence_db
    volumes:
    - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nest_backend
    image: backend
    restart: always
    expose:
      - "3000"
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_REDIRECT_URI: "https://localhost:8443/api/auth/google/callback"
    volumes:
      - ./backend:/usr/src/app   # Synchronise ton code source
      - /usr/src/app/node_modules  # Empêche ton dossier local d'écraser les packages du container
      # - /usr/src/app/dist  # Optionnel: protège le dossier de build
    depends_on:
      - db
    # On s'assure que Nest tourne en mode watch (vérifie ton package.json)
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: frontend
    image: frontend
    restart: always
    expose:
      - "5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    stdin_open: true
    # On force l'hôte et le polling via la commande
    command: npm run dev -- --host 0.0.0.0

  gateway:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend

volumes:
  pgdata: